from typing import Final

display_colors: Final = {
    'Boundboxes':{
        'scell': {'color': 'white', 'facecolor': 'none', 'edgecolor': 'royalblue', 'alpha': 1.0, 'linewidth': 1.0, 'zorder': 15 },
        'module': {'color': 'none', 'facecolor': 'none', 'edgecolor': 'red', 'alpha': 1.0, 'linewidth': 1.0, 'zorder': 16 },
        'abstractModule': {'color': 'white', 'facecolor': 'none', 'edgecolor': 'purple', 'alpha': 1.0, 'linewidth': 1.0, 'zorder': 16 },
     },
    'CellPolygons': {
        'Oxide Diffusion': {'color': 'olive', 'facecolor': 'olive', 'edgecolor': 'black', 'alpha': 0.95, 'linewidth': 1.0, 'zorder': 3 },
        'Gate Poly': {'color': 'fuchsia', 'facecolor': 'fuchsia', 'edgecolor': 'black', 'alpha': 0.9, 'linewidth': 1.0, 'zorder': 4},
        'Contact': {'color': 'salmon', 'facecolor': 'salmon', 'edgecolor': 'black', 'alpha': 0.9, 'linewidth': 1.0, 'zorder': 5},
        'N Implant': {'color': 'mediumaquamarine', 'facecolor': 'mediumaquamarine', 'edgecolor': 'black', 'alpha': 0.5, 'linewidth': 0.2, 'zorder': 2},
        'P Implant': {'color': 'thistle', 'facecolor': 'thistle', 'edgecolor': 'black', 'alpha': 0.5, 'linewidth': 0.2, 'zorder': 2},
        'N Well': {'color': 'slategrey', 'facecolor': 'slategrey', 'edgecolor': 'black', 'alpha': 0.5, 'linewidth': 0.2, 'zorder': 1},
        'P Well': {'color': 'indianred', 'facecolor': 'indianred', 'edgecolor': 'black', 'alpha': 0.5, 'linewidth': 0.2, 'zorder': 1},
        'N High VT': {'color': 'darkgreen', 'facecolor': 'none', 'edgecolor': 'darkgreen', 'alpha': 1.0, 'linewidth': 2.0, 'zorder': 15},
        'N Low VT': {'color': 'plum', 'facecolor': 'none', 'edgecolor': 'plum', 'alpha': 1.0, 'linewidth': 2.0, 'zorder': 15},
        'P High VT': {'color': 'indigo', 'facecolor': 'none', 'edgecolor': 'indigo', 'alpha': 1.0, 'linewidth': 2.0, 'zorder': 15},
        'P Low VT': {'color': 'darkgoldenrod', 'facecolor': 'none', 'edgecolor': 'darkgoldenrod', 'alpha': 1.0, 'linewidth': 2.0, 'zorder': 15},
    },
    'Metals': {
        'Metal1': {'color': 'khaki', 'facecolor': 'khaki', 'edgecolor': 'black', 'alpha': 0.95, 'linewidth': 0.4, 'zorder': 4 },
        'Metal2': {'color': 'turquoise', 'facecolor': 'turquoise', 'edgecolor': 'black', 'alpha': 0.9, 'linewidth': 0.4, 'zorder': 5 },
        'Metal3': {'color': 'limegreen', 'facecolor': 'limegreen', 'edgecolor': 'black', 'alpha': 0.85, 'linewidth': 0.4, 'zorder': 6 },
        'Metal4': {'color': 'darkorange', 'facecolor': 'darkorange', 'edgecolor': 'black', 'alpha': 0.8, 'linewidth': 0.4, 'zorder': 7 },
        'Metal5': {'color': 'purple', 'facecolor': 'purple', 'edgecolor': 'black', 'alpha': 0.75, 'linewidth': 0.4, 'zorder': 8 },
        'Metal6': {'color': 'cornflowerblue', 'facecolor': 'cornflowerblue', 'edgecolor': 'black', 'alpha': 0.7, 'linewidth': 0.4, 'zorder': 9 },
        'Metal7': {'color': 'red', 'facecolor': 'red', 'edgecolor': 'black', 'alpha': 0.65, 'linewidth': 0.4, 'zorder': 10 },
        'Metal8': {'color': 'peru', 'facecolor': 'peru', 'edgecolor': 'black', 'alpha': 0.6, 'linewidth': 0.4, 'zorder': 11 },
        'Metal9': {'color': 'olivedrab', 'facecolor': 'olivedrab', 'edgecolor': 'black', 'alpha': 0.55, 'linewidth': 0.4, 'zorder': 12 },
        'Metal10': {'color': 'gray', 'facecolor': 'gray', 'edgecolor': 'black', 'alpha': 0.5, 'linewidth': 0.4, 'zorder': 13 },
        'Metal11': {'color': 'black', 'facecolor': 'khaki', 'edgecolor': 'black', 'alpha': 0.45, 'linewidth': 0.4, 'zorder': 14 },
        'Metal12': {'color': 'black', 'facecolor': 'khaki', 'edgecolor': 'black', 'alpha': 0.4, 'linewidth': 0.4, 'zorder': 15 },
    },
    'VIAS': {
        'VIA1': {'color': 'sandybrown', 'facecolor': 'sandybrown', 'edgecolor': 'blue', 'alpha': 0.95, 'linewidth': 1.0, 'zorder': 4 },
        'VIA2': {'color': 'rosybrown', 'facecolor': 'rosybrown', 'edgecolor': 'blue', 'alpha': 0.9, 'linewidth': 1.0, 'zorder': 5 },
        'VIA3': {'color': 'navy', 'facecolor': 'navy', 'edgecolor': 'blue', 'alpha': 0.85, 'linewidth': 1.0, 'zorder': 6 },
        'VIA4': {'color': 'darkslategray', 'facecolor': 'darkslategray', 'edgecolor': 'blue', 'alpha': 0.8, 'linewidth': 1.0, 'zorder': 7 },
        'VIA5': {'color': 'plum', 'facecolor': 'plum', 'edgecolor': 'blue', 'alpha': 0.75, 'linewidth': 1.0, 'zorder': 8 },
        'VIA6': {'color': 'teal', 'facecolor': 'teal', 'edgecolor': 'blue', 'alpha': 0.7, 'linewidth': 1.0, 'zorder': 9 },
        'VIA7': {'color': 'thistle', 'facecolor': 'thistle', 'edgecolor': 'blue', 'alpha': 0.65, 'linewidth': 1.0, 'zorder': 10 },
        'VIA8': {'color': 'darkgray', 'facecolor': 'darkgray', 'edgecolor': 'blue', 'alpha': 0.6, 'linewidth': 1.0, 'zorder': 11 },
        'VIA9': {'color': 'black', 'facecolor': 'khaki', 'edgecolor': 'blue', 'alpha': 0.55, 'linewidth': 1.0, 'zorder': 12 },
        'VIA10': {'color': 'black', 'facecolor': 'khaki', 'edgecolor': 'blue', 'alpha': 0.5, 'linewidth': 1.0, 'zorder': 13 },
        'VIA11': {'color': 'black', 'facecolor': 'khaki', 'edgecolor': 'blue', 'alpha': 0.45, 'linewidth': 1.0, 'zorder': 14 },
    },
}
